# REST Client file Processor

### Create a new ticket
POST http://localhost:8080/api/v1/booking/processor/tickets
Content-Type: application/json

{
  "finalPrice": 150.00,
  "bookingTime": "2024-12-01T08:00:00Z",
  "isCancelled": false,
  "token": "TICKET-ABC123"
}

### Update ticket by ID
PATCH http://localhost:8080/api/v1/booking/processor/tickets
Content-Type: application/json

{
  "id": 1,
  "finalPrice": 160.00,
  "bookingTime": "2024-12-01T09:00:00Z",
  "isCancelled": false,
  "token": "TICKET-ABC123"
}

### Delete ticket by ID
DELETE http://localhost:8080/api/v1/booking/processor/tickets/1
Accept: application/json
