# REST Client file Status

### Get all tickets
GET http://localhost:8080/api/v1/booking/status/tickets
Accept: application/json

### Get ticket by ID
GET http://localhost:8080/api/v1/booking/status/tickets/1
Accept: application/json
