# REST Client file Auth

### Login user
POST http://localhost:8080/api/v1/identity/auth/login
Content-Type: application/json

{
  "email": "john.doe@email.com",
  "password": "Test1234$$%"
}

### Logout user
GET http://localhost:8080/api/v1/identity/auth/logout
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJqb2huLmRvZUBlbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3ODE1Njg3NjUsImV4cCI6MTc4MTU3OTU2NX0.Qg4JdxXpKZCzoK327VsL1S4D_Udd7Kyqw_hme13NlBYpo4dUHeZqDO5frYk7hdYw

### Change password
PATCH http://localhost:8080/api/v1/identity/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJqb2huLmRvZUBlbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3ODE2MzA4NTksImV4cCI6MTc4MTY0MTY1OX0.3ZbDmOgrz9bQTCtIC9JEnO-oKYelIUC9ynoonEGft8PzWmGmBoSgDAAIAq9bfnCH

{
  "email": "john.doe@email.com",
  "password": "NewPassword456!",
  "newPassword": "Test1234$$%"
}
