# REST Client file Auth

### Login user
POST http://localhost:8080/api/v1/identity/auth/login
Content-Type: application/json

{
  "email": "john.doe@email.com",
  "password": "Test1234$$%"
}

### Logout user
GET http://localhost:8080/api/v1/identity/auth/logout
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJqb2huLmRvZUBlbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3ODE3MzI5NjEsImV4cCI6MTc4MTc0Mzc2MX0.IVFRSlxLm-rFjf7ZsVegYfaPRRBsZl1JwWa8u4y5F2Af_rgOiKbktSfUCpYd8PvV

### Change password
PATCH http://localhost:8080/api/v1/identity/auth/change-password
Content-Type: application/json

{
  "email": "john.doe@email.com",
  "password": "NewPassword456!",
  "newPassword": "Test1234$$%"
}
