# REST Client file Driver - Admin Management

### Get all drivers
GET http://localhost:8080/api/v1/identity/drivers
Accept: application/json

### Get driver by ID
GET http://localhost:8080/api/v1/identity/drivers/1
Accept: application/json

### Create a new driver
POST http://localhost:8080/api/v1/identity/drivers
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "isActive": true,
  "licenseNumber": "DR12345X",
  "phoneNumber": "+541112345678"
}

### Update driver by ID (optional fields)
PATCH http://localhost:8080/api/v1/identity/drivers
Content-Type: application/json

{
  "id": 5,
  "firstName": "John",
  "lastName": "Smith",
  "isActive": true,
  "licenseNumber": "DR54321Y",
  "phoneNumber": "+541199876543"
}

### Delete driver by ID
DELETE http://localhost:8080/api/v1/identity/drivers/5
Accept: application/json
