# REST Client file Register

### Create a new user
POST http://localhost:8080/api/v1/identity/register
Content-Type: application/json

{
  "firstName": "Esteban",
  "lastName": "Quito",
  "email": "esteban.quito@gmail.com",
  "password": "Test1234$$%"
}
