# REST Client file Register

### Create a new user
POST http://localhost:8080/api/v1/identity/register
Content-Type: application/json

{
  "firstName": "John2",
  "lastName": "Doe2",
  "email": "john.doe2@email.com",
  "password": "Test1234$$%"
}
