# REST Client file Architect

### Create a new bus
POST http://localhost:8080/api/v1/fleet/architect/buses
Content-Type: application/json

{
  "plateNumber": "CDV-5678",
  "totalCapacity": 40,
  "isActive": true
}

### Create a new seat
POST http://localhost:8080/api/v1/fleet/architect/seats
Content-Type: application/json

{
  "letter": "A",
  "number": 1,
  "isActive": true,
  "idBus": 1,
  "idSeatType": 1
}

### Create a new seat type
POST http://localhost:8080/api/v1/fleet/architect/seat-types
Content-Type: application/json

{
  "name": "Basic",
  "upcharge": 0.00
}

### Update bus by ID
PATCH http://localhost:8080/api/v1/fleet/architect/buses
Content-Type: application/json

{
  "id": 2,
  "totalCapacity": 45
}

### Update seat by ID
PATCH http://localhost:8080/api/v1/fleet/architect/seats
Content-Type: application/json

{
  "id": 1,
  "idSeatType": 2
}

### Update seat type by ID
PATCH http://localhost:8080/api/v1/fleet/architect/seat-types
Content-Type: application/json

{
  "id": 1,
  "name": "PremiumPlus",
  "upcharge": 35.50
}

### Delete bus by ID
DELETE http://localhost:8080/api/v1/fleet/architect/buses/1
Accept: application/json

### Delete seat by ID
DELETE http://localhost:8080/api/v1/fleet/architect/seats/1
Accept: application/json

### Delete seat type by ID
DELETE http://localhost:8080/api/v1/fleet/architect/seat-types/2
Accept: application/json
