# REST Client file Catalog

### Get all trips
GET http://localhost:8080/api/v1/journeys/catalog/trips
Accept: application/json

### Get all trips by fields
GET http://localhost:8080/api/v1/journeys/catalog/trips/search
Content-Type: application/json

{
  "startBasePrice": 200,
  "endBasePrice": 210
}

### Get trip by ID
GET http://localhost:8080/api/v1/journeys/catalog/trips/2
Accept: application/json

### Get all locations
GET http://localhost:8080/api/v1/journeys/catalog/locations
Accept: application/json

### Get all locations by fields
GET http://localhost:8080/api/v1/journeys/catalog/locations/search
Content-Type: application/json

{
  "state": "California"
}

### Get location by ID
GET http://localhost:8080/api/v1/journeys/catalog/locations/1
Accept: application/json
