# REST Client file Catalog

### Get all trips
GET http://localhost:8080/api/v1/journeys/catalog/trips?page=0&size=10
Accept: application/json

### Get all trips by fields
POST http://localhost:8080/api/v1/journeys/catalog/trips/search?page=0&size=10
Content-Type: application/json

{
  "startDepartureDate": "2026-06-20T12:00:00Z"
}

### Get all available trips
GET http://localhost:8080/api/v1/journeys/catalog/trips/available?page=0&size=10
Accept: application/json

### Get all available trips by fields
POST http://localhost:8080/api/v1/journeys/catalog/trips/available/search?page=0&size=10
Content-Type: application/json

{
  "startDepartureDate": "2026-06-20T12:00:00Z"
}

### Get available seats for trip
GET http://localhost:8080/api/v1/journeys/catalog/trips/3/available/seats
Accept: application/json

### Get trip by ID
GET http://localhost:8080/api/v1/journeys/catalog/trips/3
Accept: application/json

### Get all locations
GET http://localhost:8080/api/v1/journeys/catalog/locations?page=0&size=10
Accept: application/json

### Get all locations by fields
POST http://localhost:8080/api/v1/journeys/catalog/locations/search?page=0&size=10
Content-Type: application/json

{
  "state": "ba"
}

### Get location by ID
GET http://localhost:8080/api/v1/journeys/catalog/locations/1
Accept: application/json
