# REST Client file Inventory

### Create a new trip
POST http://localhost:8080/api/v1/journeys/inventory/trips
Content-Type: application/json

{
  "departureDate": "2039-12-01T08:00:00Z",
  "arrivalDate": "2039-12-01T14:00:00Z",
  "basePrice": 150.00,
  "idBus": 1,
  "idDriver": 2,
  "idLocationOrigin": 1,
  "idLocationDestination": 2
}

### Create a new location
POST http://localhost:8080/api/v1/journeys/inventory/locations
Content-Type: application/json

{
  "cityName": "Buenos Aires",
  "state": "BA",
  "postalCode": "1000"
}

### Update trip by ID
PATCH http://localhost:8080/api/v1/journeys/inventory/trips
Content-Type: application/json

{
  "id": 5,
  "idLocationOrigin": 2,
  "idLocationDestination": 1
}

### Update location by ID
PATCH http://localhost:8080/api/v1/journeys/inventory/locations
Content-Type: application/json

{
  "id": 1,
  "cityName": "Mendoza",
  "state": "MZ"
}

### Delete trip by ID
DELETE http://localhost:8080/api/v1/journeys/inventory/trips/2
Accept: application/json

### Delete location by ID
DELETE http://localhost:8080/api/v1/journeys/inventory/locations/1
Accept: application/json
