# REST Client file Inventory

### Create a new trip
POST http://localhost:8080/api/v1/journeys/inventory/trips
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJqb2huLmRvZUBlbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3ODE5NTU4ODEsImV4cCI6MTc4MTk2NjY4MX0.BK2TIXIDlUFElI7LQ-2sD31wmFl6brwnEWu8b9sfHk0mgltvRb423TMMxu2Bi9hM

{
  "departureDate": "2026-06-22T12:00:00Z",
  "arrivalDate": "2026-06-22T20:00:00Z",
  "basePrice": 150.00,
  "busId": 2,
  "driverId": 3,
  "locationOriginId": 2,
  "locationDestinationId": 1
}

### Update trip by ID
PATCH http://localhost:8080/api/v1/journeys/inventory/trips
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJqb2huLmRvZUBlbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3ODE4ODQ4ODcsImV4cCI6MTc4MTg5NTY4N30.1U0zGRV0dFgcjpAMgbnKCnFp0fIadVGBBki28EcKhCxIWOJEZrkwpLmLPx0rGqXg

{
  "id": 2,
  "departureDate": 300.00
}

### Delete trip by ID
DELETE http://localhost:8080/api/v1/journeys/inventory/trips/6
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJqb2huLmRvZUBlbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3ODIwNDcyNDQsImV4cCI6MTc4MjA1ODA0NH0.carSle-qcDI1w7JC388uNqgSrPzYhh4VaMS-6gJRbadN9i3P6gPaXQsw6mWb3quJ

### Create a new location
POST http://localhost:8080/api/v1/journeys/inventory/locations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJqb2huLmRvZUBlbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3ODE5MTcyMjQsImV4cCI6MTc4MTkyODAyNH0.YslcQfvFFLgcyDAtmkwNJXakRQUdf7ShrIb0Vwtvovlu0ohcmDlCdGC3VkGPBYPX

{
  "id": 1,
  "cityName": "Buenos Aires",
  "state": "BAS",
  "postalCode": "1000"
}

### Update location by ID
PATCH http://localhost:8080/api/v1/journeys/inventory/locations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJqb2huLmRvZUBlbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3ODE1Njg3NjUsImV4cCI6MTc4MTU3OTU2NX0.Qg4JdxXpKZCzoK327VsL1S4D_Udd7Kyqw_hme13NlBYpo4dUHeZqDO5frYk7hdYw

{
  "id": 1,
  "cityName": "Mendoza",
  "state": "MZ"
}

### Delete location by ID
DELETE http://localhost:8080/api/v1/journeys/inventory/locations/6
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJqb2huLmRvZUBlbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3ODE5MTcyMjQsImV4cCI6MTc4MTkyODAyNH0.YslcQfvFFLgcyDAtmkwNJXakRQUdf7ShrIb0Vwtvovlu0ohcmDlCdGC3VkGPBYPX
